# Common configurations for all profiles
server:
  port: 8082

spring:
  application:
    name: auth-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  access-token:
    expiration: 900 # 15 minutes
  refresh-token:
    expiration: 604800 # 7 days
  id-token:
    expiration: 3600 # 1 hour

# Common service-specific settings
auth-service:
  feature:
    enabled: true
  cache:
    ttl: 3600
  api:
    timeout: 5000
