# Development-specific configurations for auth-service
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service_dev
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        register: true
        prefer-ip-address: true

server:
  port: 9000
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  access-token:
    expiration: 900 # 15 minutes
  refresh-token:
    expiration: 604800 # 7 days
  id-token:
    expiration: 3600 # 1 hour

logging:
  level:
    com.example.authservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

auth-service:
  feature:
    debug-mode: true
