# Development-specific configurations for service1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/service1db_dev
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    com.example.clientservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

client-service:
  feature:
    debug-mode: true
