# Staging-specific configurations for Auth Service
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth_service_staging}
    username: ${DB_USER:staging_user}
    password: ${DB_PASSWORD:staging_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        register: true
        prefer-ip-address: true

server:
  port: ${SERVER_PORT:9000}
  tomcat:
    max-threads: 200
    min-spare-threads: 20
    max-connections: 5000

jwt:
  secret: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
  access-token:
    expiration: 1800 # 30 minutes
  refresh-token:
    expiration: 1209600 # 14 days

logging:
  level:
    root: INFO
    com.example.authservice: INFO
    org.springframework.security: INFO
  file:
    name: /var/log/auth-service/application-staging.log
    max-size: 100MB
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 100MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      environment: staging
