server:
  port: 8081

spring:
  application:
    name: service1
  datasource:
    url: jdbc:postgresql://localhost:5432/service1db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

# Service-specific settings
service1:
  feature:
    enabled: true
  cache:
    ttl: 3600
  api:
    timeout: 5000
