spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - PreserveHostHeader
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200
                redis-rate-limiter.requestedTokens: 1
        - id: client-service-route
          uri: lb://client-service
          predicates:
            - Path=/api/users/**
          filters:
            - PreserveHostHeader
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200
                redis-rate-limiter.requestedTokens: 1
      httpclient:
        connect-timeout: 1000
        response-timeout: 3s
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

server:
  tomcat:
    max-threads: 400
    min-spare-threads: 40
    max-connections: 10000
    accept-count: 100
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048

logging:
  level:
    org.springframework.cloud.gateway: WARN
    org.springframework.web: WARN
    com.example.gateway: WARN
  file:
    name: /var/log/gateway/application-prod.log
    max-size: 500MB
  logback:
    rollingpolicy:
      max-history: 60
      max-file-size: 500MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: gateway-service
      environment: production
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 10ms,50ms,100ms,200ms,500ms
