server:
  port: 8082

spring:
  application:
    name: service2
  mongodb:
    uri: mongodb://localhost:27017/service2db

# Service-specific settings
service2:
  batch:
    size: 100
  retry:
    max-attempts: 3
    initial-interval: 1000
  feature-flags:
    new-ui: true
    beta-features: false
